package com.ab.utils;

import org.springframework.stereotype.Component;

@Component
public class ItemCode {

	public String generateItemCode() {

		int min = 100;
		int max = 900;

		int autoGeneratedItemCode = (int) Math.floor(Math.random() * (max - min - 1) + min);

		System.out.println(autoGeneratedItemCode);

		String s = String.valueOf(autoGeneratedItemCode);

		return s;

	}

} // end of class
